---

# Aptitude
- name: Install Git with APT
  apt:
    name:
    state: present
  when: ansible_pkg_mgr == 'apt'

# Homebrew
- name: Install Git with Homebrew
  homebrew:
    name: git
    state: present
  become: true
  become_user: "{{ git_homebrew_user }}"
  when: ansible_pkg_mgr == 'homebrew'

- name: Install Git extras with Homebrew
  homebrew:
    name:
      - git-extras
      - hub
    state: present
  become: true
  become_user: "{{ git_homebrew_user }}"
  when: git_extras and ansible_pkg_mgr == 'homebrew'

# Yum
- name: Install Git (Yum)
  yum:
    name: git-all
    state: present
  when: ansible_pkg_mgr == 'yum'

# Other package managers
- fail: msg="{{ ansible_pkg_mgr }} is not a supported package manager (Aptitude, Homebrew or Yum are supported)"
  when: ansible_pkg_mgr != 'apt' and ansible_pkg_mgr != 'yum' and ansible_pkg_mgr != 'homebrew'
